language: shell
dist: focal
os: linux
virt: vm
group: edge
arch:
  - arm64-graviton2
  - amd64

env:
  global:
before_install:
  - openssl aes-256-cbc -K $encrypted_ddb265ce0382_key -iv $encrypted_ddb265ce0382_iv -in iotdevice-test-masahiro.login.enc -out iotdevice-test-masahiro.login -d
addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic

script:
  - snapcraft push *.snap

after_failure:
  - sudo journalctl -u snapd
deploy:
  - provider: snap
    snap: iot*.snap
    channel: edge
    skip_cleanup: true
